const word = [{topicRus:'Одежда',
               topicSpain: 'Ropa',
                setRus: ['Платье', 'Галстук', 'Ремень', 'Костюм', 'Носки' ,'Брюки', 'Рубашка', 'Футболка',
                         'Туфли', 'Сапоги', 'Одежда', 'Юбка', 'Шляпа', 'Пальто', 'Шуба', 'Свитер', 'Куртка'],
                setSpain:['Vestido', 'Corbata', 'Cinturón', 'Traje', 'Calcetines', 'Pantalones', 'Camisa', 'Camiseta',
                'Zapatos', 'Botas', 'Ropa', 'Falda', 'Sombrero', 'Abrigo', 'Abrigo De Piel', 'Suéter','Chaqueta']},
                {topicRus: 'Числа',
                topicSpain: 'Números',
                setRus: ['один', 'два', 'три', 'четыре', 'пять', 'шесть', 'семь', 'восемь', 'девять', 'десять',
                         'одиннадцать', 'двенадцать', 'тринадцать', 'четырнадцать', 'пятнадцать', 'шестнадцать',
                         'семнадцать', 'восемнадцать', 'девятнадцать', 'двадцать', 'двадцать один', 'двадцать два',
                         'тридцать', 'сорок', 'пятьдесят'],
                setSpain:['uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis', 'siete', 'ocho', 'nueve', 'diez',
                          'once', 'doce', 'trece', 'catorce', 'quince', 'dieciséis', 'diecisiete', 'diecinueve',
                          'veinte', 'veintiuno', 'veintidós', 'treinta', 'cuarenta','cincuenta']},
               {topicRus: 'Цвета',
                topicSpain: 'Colores',
                setRus: ['белый', 'черный', 'красный', 'зеленый', 'синий', 'лиловый', 'коричневый',
                         'прозрачный', 'оранжевый', 'желтый', 'розовый', 'светлый', 'темный', 'бежевый', 'фиолетовый'],
                setSpain:['blanco', 'negro', 'rojo', 'verde', 'azul', 'malva', 'marrón', 'transparente', 'naranja',
                          'amarillo', 'rosa', 'claro', 'oscuro', 'beige', 'púrpura']},
                {topicRus: 'Глаголы',
                topicSpain: 'Verbos',
                setRus: ['иметь', 'хотеть', 'играть', 'читать', 'писать', 'помнить', 'забывать', 'терять', 'выигрывать',
                         'продолжать', 'получать', 'есть', 'пить', 'спать', 'ходить', 'идти', 'бежать', 'готовить', 'сушить',
                         'красить', 'обещать', 'закрывать', 'открывать', 'достигать', 'пробовать', 'начинать', 'заканчивать',
                         'говорить', 'сказать', 'решить', 'возврашаться', 'добывать', 'смотреть', 'видеть', 'слышать'],
                setSpain:['tener',' querer',' jugar',' Leer',' escribir',' recordar',' olvidar',' perder',' ganar',' continuar',
                          'recibir',' comer',' beber',' dormir',' caminar',' ir',' correr',' cocinar',' secar',' pintar',
                          ' prometer',' cerrar',' abrir',' alcanzar',' intentar',' empezar',' terminar',' hablar',' decir',
                          ' decidir',' volver',' extraer',' mirar',' ver','oír']},
                // {topicRus: ,
                // topicSpain: ,
                // setRus: [],
                // setSpain:[]},
            ]
            export default word;
